#!/bin/sh
set -e
if [ "$1" = configure ] && [ -d /run/systemd/system ]; then
	systemctl daemon-reload
	systemctl enable broadcastwedge.service >/dev/null 2>&1 || true
	systemctl restart broadcastwedge.service || true
fi
